controllers/DashboardController.php
<?php
namespace app\controllers;

use app\models\ChangeEmail;
use app\models\ChangePassword;
use app\models\Companies;
use app\models\CompanyContact;
use app\models\Profile;
use app\models\Seaman;
use app\models\SeamanCertificateOfCompetency;
use app\models\SeamanCertificateOfProficiency;
use app\models\SeamanDocumentScan;
use app\models\SeamanMedicalDocument;
use app\models\SeamanTravelDocument;
use app\models\TermsForm;
use app\models\TermsOfService;
use app\models\TravelDocument;
use app\models\User;
use app\models\UserFile;
use Yii;
use app\models\Users;
use app\models\Competency;
use yii\base\ErrorException;
use yii\base\InvalidParamException;
use yii\bootstrap\ActiveForm;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\ShareSeamanForm;
use yii\web\Response;
use yii\data\ActiveDataProvider;
use kartik\mpdf\Pdf;
use app\models\ComposeForm;

/**
 * Site controller
 */
class DashboardController extends Controller
{
    public function init()
    {

        parent::init();
        if (!Yii::$app->user->isGuest) {
            $user = Users::findOne(Yii::$app->user->id);
            $user->last_seen = date('Y-m-d H:i:s');
            $user->save(false, ["last_seen"]);
        }
    }
	 public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
    	$this->layout="dashboard";

    	if(Yii::$app->user->isGuest){
    		return $this->goHome();
    	}
        $labels = [];
        if (Yii::$app->request->get('id') == 2) {
            $data = Users::getChartDataMonth();
            $m = date('m');
            $y = date('Y');
            $days_count = cal_days_in_month(CAL_GREGORIAN, $m, $y);

            for ($i = 1; $i <= $days_count; $i++) {
                $labels[] = $i . '.' . $m;
            }
        } elseif (Yii::$app->request->get('id') == 3) {
            $data = Users::getChartDataYear();
            $labels = [
                'January',
                'February',
                'March',
                'April',
                'May',
                'June',
                'Juli',
                'August',
                'September',
                'October',
                'November',
                'December'
            ];
        } elseif (Yii::$app->request->get('id') == 4) {
            $data = Users::getChartDataAll();
            foreach ($data as $item) {
                $labels[] = $item['pick'];
            }
        } else {
            $data = Users::getChartDataWeek();
            $labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursdays', 'Friday', 'Saturday', 'Sunday'];
        }

        return $this->render('index', [
            'data'=>$data,
            'labels' => $labels
        ]);

    }

    public function actionShare()
    {
    	$this->layout="dashboard";
    	$model = new ShareSeamanForm();
        $model_s = new Companies();
    	
    	return $this->render('share',[
    		'model'=>$model,
            'model_s'=>$model_s,
    	]);
    }

    public function actionExport()
    {
        $this->layout = "dashboard";
        $model = new ShareSeamanForm();

        if($model->load(Yii::$app->request->post())){
            $post = Yii::$app->request->post('ShareSeamanForm');
            $link = str_replace('http://','',$post['link']);
            $link = explode('/',$link);
            $n = count($link);
            $pid = str_replace('id','',$link[$n-1]);
            if (($profile = Profile::findOne($pid)) != null) {
                if (($user = Users::findOne($profile->user_id)) != null && ($user->role == 'seaman')) {
                    $id = $user->id;
                    $data = Seaman::findOne(['user_id'=>$id]);
                    //VarDumper::dump($id);die;
                    $content = $this->renderPartial('_seaman-pdf',[
                        'post'=>$post,
                        'data'=>$data,
                    ]);

                    $pdf = new Pdf([
                        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
                        'content' => $content,
                        'format'=> Pdf::FORMAT_A4,
                        'destination'=>Pdf::DEST_DOWNLOAD,
                        'cssFile'=>Yii::$app->basePath.'/web/css/pdf.css',
                        'filename'=>Yii::$app->name.' - '.$data->first_name.' '.$data->last_name,
                        'options' => [
                            'title' => $data->first_name.' '.$data->last_name
                        ],
                        'methods' => [
                            'SetHeader' => ['Generated By: '.Yii::$app->name.' ||Generated On: ' . date("F d, Y")],
                            'SetFooter' => ['|Page {PAGENO}|'],
                        ]
                    ]);
                    return $pdf->render();
                } else {
                    Yii::$app->session->setFlash('error', 'This user is Company');
                }
            }else{
                Yii::$app->session->setFlash('error', 'This user does not exist');
            }
        }

        return $this->render('seaman-export', [
            'model' => $model,
        ]);
    }


    public function actionLoadseaman()
    {
        $link = str_replace('http://','',Yii::$app->request->get('id'));
        $link = explode('/',$link);
        $n = count($link);
        $pid = str_replace('id','',$link[$n-1]);
        $id = Profile::findOne($pid)->user_id;
        $seaman = Seaman::findOne(['user_id'=>$id])->id;
        $scans = SeamanDocumentScan::findAll(['seaman_id'=>$seaman]);
        $docs = [];
        foreach($scans as $item){
            $coc = SeamanCertificateOfCompetency::getAllByScan($item->id);
            foreach($coc as $c){
                $docs[] = $c;
            }
            $tr = SeamanTravelDocument::getAllByScan($item->id);
            foreach($tr as $t){
                $docs[] = $t;
            }
            $med = SeamanMedicalDocument::getAllByScan($item->id);
            foreach($med as $m){
                $docs[] = $m;
            }
            $prof = SeamanCertificateOfProficiency::getAllByScan($item->id);
            foreach($prof as $p){
                $docs[] = $p;
            }
        }
        if(!empty($docs)) {
            $html = '';
            foreach ($docs as $item) {
                $html .= '<option value="' . $item->scan_id . '">' . $item->docType['name'] . '</option>';
            }
            echo $html;
        }
    }

    public function actionMails()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $data = CompanyContact::find()->select('email')->andFilterWhere(['like', 'email', Yii::$app->request->get('term')])->all();
        $arr = ArrayHelper::map($data,'email','email');
        return $arr;
    }

    public function actionTerms()
    {
        $this->layout="dashboard";
        $model = new TermsOfService();
        $data = $model->find()->orderBy(['position'=>SORT_ASC])->all();
        return $this->render('terms',[
            'model'=>$model,
            'data'=>$data
        ]);
    }

    public function actionTermsform()
    {
        $model = new TermsOfService();
        $data = '';
        if($model->load(Yii::$app->request->get('id'))){
           $data = $model->findOne(Yii::$app->request->get('id'));
        }
        if($model->load(Yii::$app->request->post())){
            $post = Yii::$app->request->post('TermsOfService');
            if(!empty($post['id'])){
                $updete_model = TermsOfService::findOne($post['id']);
                $updete_model->section_name = $post['section_name'];
                $updete_model->text = $post['text'];
                $updete_model->save();
            }else{
                $model = new TermsOfService();
                $model->section_name = $post['section_name'];
                $model->text = $post['text'];
                $model->save();
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        return $this->renderAjax('terms-form',[
            'model'=>$model,
            'data'=>$data
        ]);
    }

    public function actionSavetermorder()
    {
        $model = new TermsForm();
        $data = Yii::$app->request->get();
        $model->updatePosition($data);
    }

    public function actionGetDocs($id)
    {
        $uid = Profile::findOne($id)->user_id;
        $model = Seaman::findOne(['user_id' => $uid]);
        $options = '';
        $data_key = ['competency', 'travelDocs'];
        foreach ($data_key as $keyname) {
            $keyitem = $model->{$keyname};
            if (is_array($keyitem)) {
                foreach ($keyitem as $item) {
                    if (!empty($item->scan_id)) {
                        $options .= '<option value="' . $item->id . '-' . $item->scan_id . '">' . $item->docType->name . '</option>';
                    }
                }
            } else {
                echo $keyitem->scan_id;
                echo "<br>";
            }
            echo $options;
        }
    }
    public function actionParticulars()
    {
        $this->layout = "dashboard";
        $model = new Seaman();

        $query = new ActiveQuery(Seaman::className());
        $error = null;
        if(Yii::$app->request->get('link')){

views/dashboard/compose.php
<?php
/* @var $this yii\web\View */
/* @var $model \app\models\ComposeForm */
/* @var $form ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use vova07\imperavi\Widget;

$this->title = 'Compose message';

?>

<div class="block clearfix">
    <div class="bt clearfix">
        <h1>Compose message</h1>
    </div>
    <?php $form = ActiveForm::begin([
        'id' => 'compose',
        'options' => ['class' => 'compose_form'],
        'validateOnBlur' => false,
        'validateOnChange' => false,
    ]); ?>

    <table class="compose table">
        <tr>
            <td class="heading" colspan="2">Headers</td>
        </tr>
        <tr>
            <td class="f-tit"><span class="req">*</span> To</td>
            <td>
                <?= $form->field($model, 'to')->textInput(['placeholder' => 'Enter recipient’s email'])->label(false) ?>
            </td>
        </tr>
        <tr>
            <td class="f-tit"><span class="req">*</span> From</td>
            <td>
                <?= $form->field($model, 'from', [
                    'template' => '{input} <span class="input-group-addon" id="basic-addon3">@crewix.com</span>',
                    'options' => ['class' => 'input-group'],
                ])->textInput(['placeholder' => 'Enter username', 'aria-describedby' => 'basic-addon3']); ?>
            </td>
        </tr>
        <tr>
            <td class="f-tit"><span class="req">*</span> Subject</td>
            <td>
                <?= $form->field($model, 'subject')->textInput(['placeholder' => 'Enter subject'])->label(false) ?>
            </td>
        </tr>
        <tr>
            <td class="heading" colspan="2">Message</td>
        </tr>
        <tr>
            <td colspan="2">
                <?= $form->field($model, 'message')->widget(Widget::className(), [
                    'settings' => [
                        'minHeight' => 200,
                        'buttons' => ['format', 'bold', 'italic', 'deleted', 'unorderedlist', 'orderedlist', 'link']
                    ]
                ])->label(false); ?>
            </td>
        </tr>
        <tr>
            <td class="heading" colspan="2">
                Attachments
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="attachments">
                    <div class="item">
                        <div class="img">
                            <div class="images">
                                <i class="fa fa-plus-circle"></i>
                                <svg class="loader" viewBox="0 0 100 100">
                                    <circle class="one" r="40" cx="50" cy="50"/>
                                    <circle class="two" r="40" cx="50" cy="50"/>
                                </svg>
                            </div>
                            <?= $form->field($model, 'files[]',
                                ['options' => ['class' => 'attach']])->fileInput()->label(false); ?>
                        </div>
                        <div class="filename"></div>
                        <div class="remove-file">Remove</div>
                    </div>
                </div>
            </td>
        </tr>
    </table>
    <div class="bot">
        <?= Html::submitButton('Send', ['class' => 'btn btn-primary', 'name' => 'compose-button', 'id' => 'compose-but']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<script type="text/template" id="new-file">
    <?= $this->render('/dashboard/new-file', [
        'model' => $model,
    ]); ?>
</script>

<script>
    $("select").selectmenu({
        width: '100%'
    });
    window.FileAPI = {
        html5: !!1,
        staticPath: '/js/filapi/',
        flashUrl: '/js/filapi/FileAPI.flash.swf',
        flashImageUrl: '/js/filapi/FileAPI.flash.image.swf'
    };
</script>
<script src="/js/fileapi/FileAPI.html5.js"></script>
<script>
    $('body').on('change','.attach', function (evt) {
        $(this).parent().find('.images').find('i').hide();
        $(this).parent().find('.images').find('svg').show();
        var f = evt.target.files[0];
        var reader = new FileReader();
        reader.readAsText(f);
        reader.onload = function (theFile) {
            //console.log(theFile);
            return function (e) {
                console.log('>>>>>>>>>>>');
                if (theFile.size > 25000000) {
                    alert('Images size more then 25MB');
                    return false;
                }
            };
        };


        var i = $(this);

        FileAPI.upload({
            url: '/dashboard/upload-attachment',
            files: {src: f},
            data: {'_csrf': '<?=Yii::$app->request->getCsrfToken()?>'},
            imageTransform: {
                width: 350,
                height: 450,
                preview: true
            },
            progress: function (evt) {
                var a = (evt.loaded / evt.total) * 360;
                i.parents('.item').find('.images').find('svg').find('.two').css({'stroke-dasharray': '' + a + ' 300'});
            },
            complete: function (err, xhr) {
                var res = JSON.parse(xhr.responseText)
            },
            filecomplete: function (err, xhr, file) {
                var res = JSON.parse(xhr.responseText);
                FileAPI.Image(f).preview(100, 100).get(function (err, img) {
                    setTimeout(function () {
                        i.parents('.item').find('.img').css({'border': '3px solid #4f8ec4'});
                        i.parents('.item').find('.images').find('svg').hide();
                        i.hide();
                        var n = file.name.length;
                        if(n>13){
                            var ext = file.name.split('.').pop();
                            var name = file.name.replace(/\.[^/.]+$/, '');
                            var nname = name.slice(0,(0-n+13));
                            var filename = nname+'... .'+ext
                            console.log(filename);
                        }else{
                            var filename = file.name;
                        }
                        i.parents('.item').find('.filename').text(filename);
                        i.parents('.item').find('.remove-file').show();
                        i.parents('.item').find('.images').append('<i class="' + res.ico + ' file-ico"></i>');
                    }, 300);
                    var fileinfo = '{"name":"' + res.file + '","size":"' + file.size + '"}';
                    i.parents('.item').find('.file-info').find('input').val(fileinfo);
                    var c = $('.attachments .item').length;
                    if(c<5){
                        var tpl = $('#new-file').html();
                        $('.attachments').append(tpl);
                    }
                });
            }
        });
        reader.readAsDataURL;
    });
</script>

views/dashboard/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Countries;
use app\models\Users;
use kartik\file\FileInput;
use dosamigos\chartjs\ChartJs;
use yii\db\Query;
use yii\db\QueryBuilder;
use yii\widgets\Pjax;

$this->title = 'Dashboard';
$this->registerJsFile('/js/bootstrap.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

?>

<div class="stats">
	<div class="item"></div>
	<div class="item"></div>
	<div class="item"></div>
	<div class="item"></div>
</div>
<div class="block graph">
    <div class="bt clearfix">
        <h1 class="pull-left">User growth rate</h1>
        <div class="dropdown pull-right">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="true">
                This week
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu chart-view" aria-labelledby="dropdownMenu1">
                <li><a href="#" data-id="1">This week</a></li>
                <li><a href="#" data-id="2">This month</a></li>
                <li><a href="#" data-id="3">This year</a></li>
                <li><a href="#" data-id="4">All time</a></li>
            </ul>
        </div>
    </div>

    <div class="chart">
        <?php Pjax::begin(['id' => 'chart', 'enablePushState' => false]); ?>
        <?php
        $month = [];
        $pick = [];
        foreach ($data as $item) {
            $month[] = $item['count_month'];
            $pick[] = $item['pick'];
        }

        ?>
        <?= ChartJs::widget([
            'type' => 'Line',
            'options' => [
                'height' => 400,
                'width' => 800,

            ],
            'data' => [
                'labels' => $labels,
                'datasets' => [
                    [
                        'fillColor' => "rgba(151,187,205,0.5)",
                        'strokeColor' => "rgba(151,187,205,1)",
                        'pointColor' => "rgba(151,187,205,1)",
                        'pointStrokeColor' => "#fff",
                        'data' => $month,

                    ]
                ]
            ]
        ]); ?>
        <?php Pjax::end() ?>
    </div>

</div>

<?php
$this->registerJs('
        $(\'body\').on(\'click\',\'.chart-view li a\',function(){
            var $el = $(this);
            var id = $el.attr(\'data-id\');
            $.pjax({
                url:\'/dashboard\',
				container: \'#chart\',
        		push: false,
				data: {id:id},
            }).done(function(){
                $(\'.dropdown-toggle\').html($el.text()+\'<span class="caret"></span>\').attr(\'aria-expanded\',false);
                $(\'.dropdown\').removeClass(\'open\');
            });
            return false;
        });
    ', \yii\web\View::POS_READY);
?>

views/dashboard/new-file.php
<?php
    use yii\bootstrap\Html;
?>

<div class="item">
    <div class="img">
        <div class="images">
            <i class="fa fa-plus-circle"></i>
            <svg class="loader" viewBox="0 0 100 100">
                <circle class="one" r="40" cx="50" cy="50"/>
                <circle class="two" r="40" cx="50" cy="50"/>
            </svg>
        </div>
        <div class="attach field-composeform-files">
            <?=Html::activeFileInput($model,'files[]',['class' => 'attach'])?>
        </div>

    </div>
    <div class="filename"></div>
    <div class="remove-file">Remove</div>
</div>

views/dashboard/particulars.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
use yii\widgets\ListView;

$this->title = 'Dashboard';


?>
<div class="block">
    <div class="bt">
        <h1>Share seaman</h1>
    </div>
    <?php $form = ActiveForm::begin([
        'id' => 'particulars',
        'options' => ['class' => 'family_form'],
        'validateOnBlur' => false,
        'validateOnChange' => false,
    ]); ?>
    <table class="col-lg-12">
        <tr>
            <td colspan="2" class="heading">
                User
            </td>
        </tr>
        <tr>
            <td class="f-tit">User</td>
            <td>
                <div class="info">
                    <div class="img"><img src="/images/sys/profile2.png" alt=""></div>
                    <div class="data">
                        <div class="name"></div>
                        <div class="rank"></div>
                    </div>
                </div>
                <?= $form->field($model, 'link')->textInput(['placeholder' => 'Enter users link',['class'=>'link']])->label(false); ?>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="heading">
                Particulars
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="particulars-info">
                    <?php Pjax::begin(['id' => 'particulars-block', 'enablePushState' => false]); ?>
                    <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'id' => 'part',
                        'emptyText' => '',
                        'emptyTextOptions' => ['class' => 'empty-val'],
                        'itemOptions' => ['class' => 'item'],
                        'summary' => '',
                        'itemView' => 'particulars/_item',
                    ]) ?>
                    <?php Pjax::end(); ?>
                </div>
            </td>
        </tr>
    </table>
    <div class="bot">
        <div class="form-group">
            <?= Html::Button('Generate',
                ['class' => 'btn btn-primary', 'name' => 'signup-button', 'id' => 'generate']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php
    $this->registerJs('
        $(document).on(\'click\',\'#generate\',function(){
            var val = $(\'#seaman-link\').val();
            $.pjax({
				url:\'/dashboard/particulars\',
				container: \'#particulars-block\',
        		fragment: \'#part\',
				data: {link:val},
				push:false,
			}).done(function(data) {
			    console.log(data);
			    if(data==\'<title>Dashboard</title>                    <div id="part" class="list-view"><div class="empty-val"></div></div>                    \'){
			        $(\'#particulars-block\').addClass(\'disabled\');
			        $.notify(\'User does not exists or this user is Company\', "error");
			    }else{
			        $(\'#particulars-block\').removeClass(\'disabled\')
			    }

			});
			return false;
        })
    ',\yii\web\View::POS_READY);
?>

views/dashboard/share.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
$this->title = 'Dashboard';


?>
<div class="block">
    <div class="bt">
        <h1>Share seaman</h1>
    </div>
    <?php $form = ActiveForm::begin(['id' => 'share',
        'options' => ['class'=>'family_form'],
        'validateOnBlur' => false,
        'validateOnChange' => false,
    ]); ?>


        <table class="col-lg-12">
            <tr>
                <td colspan="2" class="heading">
                    Seaman
                </td>
            </tr>
            <tr>
                <td class="f-tit">User</td>
                <td>
                    <div class="info">
                        <div class="img"><img src="/images/sys/profile2.png" alt=""></div>
                        <div class="data">
                            <div class="name"></div>
                            <div class="rank"></div>
                        </div>
                    </div>
                    <?= $form->field($model, 'link', [
                        'template' => '<span class="input-group-addon" id="basic-addon3">http://crewix.com/id</span> {input}',
                        'options' => ['class'=>'input-group'],
                    ])->textInput(['placeholder'=>'Enter users link','aria-describedby'=>'basic-addon3']); ?>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="heading">
                    Details
                </td>
            </tr>
            <tr>
                <td class="f-tit">Send to</td>
                <td>
                    <?= $form->field($model, 'to')->widget(\yii\jui\AutoComplete::classname(), [
                        'options' => [
                            'class'=>'form-control'
                        ],
                        'clientOptions' => [
                            'source' => \yii\helpers\Url::to('/dashboard/mails'),
                        ]
                    ])->label(false) ?>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Rank</td>
                <td>
                    <?= $form->field($model, 'primary_rank_id')->dropDownList(ArrayHelper::map(\app\models\Ranks::find()->all(),'id','name'), ['prompt'=>'Select rank'])->label(false);?>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Vessel type</td>
                <td>
                    <?= $form->field($model, 'vessel_type_id')->dropDownList(ArrayHelper::map(\app\models\VesselTypes::find()->all(),'id','name'), ['prompt'=>'Select vessel type'])->label(false);?>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="heading">
                    Options
                </td>
            </tr>
            <tr>
                <td class="f-tit">View</td>
                <td>
                    <?php $model->view=1; ?>
                    <?=$form->field($model,'view')->radioList(['1'=>'Long view','2'=>'Short view'])->label(false)?>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Units of power</td>
                <td>
                    <?php $model->power=1; ?>
                    <?=$form->field($model,'power')->radioList(['1'=>'kW','2'=>'BHP'])->label(false)?>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Document scans</td>
                <td><?=$form->field($model,'scans')->dropDownList(['0'=>'No document scans'])->label(false)?></td>
            </tr>
            <tr>
                <td class="f-tit">Attach 3.5x4.5cm photo</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'photo',['class'=>'styled','name'=>'photo','id'=>'photo']);?>
                        <?=Html::label('Attach seaman\'s photo as JPG','photo')?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Contacts</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'contacts',['class'=>'styled','name'=>'contacts','id'=>'contacts']);?>
                        <?=Html::label('Include contacts in PDF','contacts')?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Notes</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'notes',['class'=>'styled','name'=>'notes','id'=>'notes']);?>
                        <?=Html::label('Include notes in PDF','notes')?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="f-tit">CV</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'cv',['class'=>'styled','name'=>'cv','id'=>'cv']);?>
                        <?=Html::label('Include CV in PDF','cv')?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Send a copy to me</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'copy_to_admin',['class'=>'styled','name'=>'copy_to_admin','id'=>'copy_to_admin']);?>
                        <?=Html::label('Send a copy to '.Yii::$app->user->identity->email,'copy_to_admin')?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="f-tit">Notify seaman</td>
                <td>
                    <div class="checkbox checkbox-primary">
                        <?=Html::checkbox(false,'notify',['class'=>'styled','name'=>'notify','id'=>'notify']);?>
                        <?=Html::label('Send a notification to seaman','notify')?>
                    </div>
                </td>
            </tr>
        </table>

    <div class="bot">
        <div class="form-group">
            <?= Html::submitButton('Save & continue', ['class' => 'btn btn-primary', 'name' => 'signup-button', 'id' => 'f_sign']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>


<script>
    $.widget( "custom.iconselectmenu", $.ui.selectmenu, {
          _renderItem: function( ul, item ) {
            var li = $( "<li>", { text: item.label } );
     
            if ( item.disabled ) {
              li.addClass( "ui-state-disabled" );
            }
     
            $( "<span>", {
              style: item.element.attr( "data-style" ),
              "class": "ui-icon " + item.element.attr( "data-class" )
            })
              .appendTo( li );
     
            return li.appendTo( ul );
          }
        });
    $('select').each(function(i,el){
        if(!$(el).parent().hasClass('countries')){
            $(el).selectmenu({
                width: '100%'
            });
        }else{
            $(el).iconselectmenu({width: '100%'}).iconselectmenu( "menuWidget").addClass( "ui-menu-icons avatar" );
        }
    });
    $('.date input').datepicker({
            format: 'dd.mm.yyyy',
        });
</script>