models/Users.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\QueryBuilder;
use yii\db\Connection;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $email
 * @property string $password
 * @property integer $role
 * @property string $date
 */
class Users extends ActiveRecord
{
    public $mail;
    public $next;
    public $name;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'password', 'account_type_id'], 'required'],
            [['account_type_id'], 'integer'],
            [['account_type_id'], 'in', 'range' => [1, 2], 'message' => 'You\'re trying to break the form'],
            [['email'], 'unique'],
            [['email'], 'email'],
            [['registration_step'], 'integer'],
            [['email', 'password'], 'string', 'max' => 255],
        ];
    }

    public function saveUser($post,$auth_key){
        $pass = Yii::$app->getSecurity()->generatePasswordHash($post['password'], 13);
        $arr = ['email'=>$post['email'],
                'password'=>$pass,
                'account_type_id'=>$post['account_type_id'],
                'auth_key'=>$auth_key,];

        return Yii::$app->db->createCommand()->insert('user',$arr)->execute();
    }

    public function saveRole($role,$id)
    {
        return Yii::$app->db->createCommand()->update('user',['role'=>$role],['id'=>$id])->execute();
    }

    public function getByMail($mail)
    {
        return static::find()->select('id')->where(['email'=>$mail])->one();
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
        return $this->auth_key;
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public static function getChartDataYear()
    {
        return Yii::$app->db->createCommand('SELECT count(*) as count_month, DATE_FORMAT(signup_date,\'%M %Y\') as pick  FROM crewix.user WHERE DATE_FORMAT(signup_date,\'%Y\') = DATE_FORMAT(now(),\'%Y\')  group by date_format(signup_date,\'%Y-%m\') ORDER BY signup_date ASC')->queryAll();
    }

    public static function getChartDataWeek()
    {
        return Yii::$app->db->createCommand('SELECT count(*) as count_month, DATE_FORMAT(signup_date,\'%W\') as pick  FROM crewix.user WHERE yearweek(`signup_date`) = yearweek(curdate())  group by date_format(signup_date,\'%W\') ORDER BY signup_date ASC')->queryAll();
    }

    public static function getChartDataMonth()
    {
        return Yii::$app->db->createCommand('SELECT
            count(*) as count_month,
            DATE_FORMAT(signup_date,\'%d.%m\') as pick
        FROM
            crewix.user
        WHERE
            DATE_FORMAT(signup_date,\'%m %Y\') = DATE_FORMAT(now(),\'%m %Y\')
        group by date_format(signup_date,\'%d %M\') ORDER BY signup_date ASC')->queryAll();
    }

    public static function getChartDataAll()
    {
        return Yii::$app->db->createCommand('SELECT
            count(*) as count_month,
            DATE_FORMAT(signup_date,\'%m.%Y\') as pick
        FROM
            crewix.user
        group by date_format(signup_date,\'%m %Y\') ORDER BY signup_date ASC')->queryAll();
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'email' => Yii::t('app', 'Mail'),
            'password' => Yii::t('app', 'Password'),
            'account_type_id' => Yii::t('app', 'U Type'),
            'date' => Yii::t('app', 'Date'),
        ];
    }

    public function getSeaman()
    {
        return $this->hasOne('app\models\Seaman', ['user_id' => 'id']);
    }

    public function getCompany()
    {
        return $this->hasOne('app\models\Companies', ['user_id' => 'id']);
    }

    public function getUserAccountType()
    {
        return $this->hasOne(UserAccountType::className(), ['id' => 'user_account_type_id']);
    }

}

controllers/DashboardController.php
<?php
namespace app\controllers;

use app\models\ChangeEmail;
use app\models\ChangePassword;
use app\models\Companies;
use app\models\CompanyContact;
use app\models\Profile;
use app\models\Seaman;
use app\models\SeamanCertificateOfCompetency;
use app\models\SeamanCertificateOfProficiency;
use app\models\SeamanDocumentScan;
use app\models\SeamanMedicalDocument;
use app\models\SeamanTravelDocument;
use app\models\TermsForm;
use app\models\TermsOfService;
use app\models\TravelDocument;
use app\models\User;
use app\models\UserFile;
use Yii;
use app\models\Users;
use app\models\Competency;
use yii\base\ErrorException;
use yii\base\InvalidParamException;
use yii\bootstrap\ActiveForm;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\ShareSeamanForm;
use yii\web\Response;
use yii\data\ActiveDataProvider;
use kartik\mpdf\Pdf;
use app\models\ComposeForm;

/**
 * Site controller
 */
class DashboardController extends Controller
{
    public function init()
    {

        parent::init();
        if (!Yii::$app->user->isGuest) {
            $user = Users::findOne(Yii::$app->user->id);
            $user->last_seen = date('Y-m-d H:i:s');
            $user->save(false, ["last_seen"]);
        }
    }
	 public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
    	$this->layout="dashboard";

    	if(Yii::$app->user->isGuest){
    		return $this->goHome();
    	}
        $labels = [];
        if (Yii::$app->request->get('id') == 2) {
            $data = Users::getChartDataMonth();
            $m = date('m');
            $y = date('Y');
            $days_count = cal_days_in_month(CAL_GREGORIAN, $m, $y);

            for ($i = 1; $i <= $days_count; $i++) {
                $labels[] = $i . '.' . $m;
            }
        } elseif (Yii::$app->request->get('id') == 3) {
            $data = Users::getChartDataYear();
            $labels = [
                'January',
                'February',
                'March',
                'April',
                'May',
                'June',
                'Juli',
                'August',
                'September',
                'October',
                'November',
                'December'
            ];
        } elseif (Yii::$app->request->get('id') == 4) {
            $data = Users::getChartDataAll();
            foreach ($data as $item) {
                $labels[] = $item['pick'];
            }
        } else {
            $data = Users::getChartDataWeek();
            $labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursdays', 'Friday', 'Saturday', 'Sunday'];
        }

        return $this->render('index', [
            'data'=>$data,
            'labels' => $labels
        ]);

    }

    public function actionShare()
    {
    	$this->layout="dashboard";
    	$model = new ShareSeamanForm();
        $model_s = new Companies();
    	
    	return $this->render('share',[
    		'model'=>$model,
            'model_s'=>$model_s,
    	]);
    }

    public function actionExport()
    {
        $this->layout = "dashboard";
        $model = new ShareSeamanForm();

        if($model->load(Yii::$app->request->post())){
            $post = Yii::$app->request->post('ShareSeamanForm');
            $link = str_replace('http://','',$post['link']);
            $link = explode('/',$link);
            $n = count($link);
            $pid = str_replace('id','',$link[$n-1]);
            if (($profile = Profile::findOne($pid)) != null) {
                if (($user = Users::findOne($profile->user_id)) != null && ($user->role == 'seaman')) {
                    $id = $user->id;
                    $data = Seaman::findOne(['user_id'=>$id]);
                    //VarDumper::dump($id);die;
                    $content = $this->renderPartial('_seaman-pdf',[
                        'post'=>$post,
                        'data'=>$data,
                    ]);

                    $pdf = new Pdf([
                        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
                        'content' => $content,
                        'format'=> Pdf::FORMAT_A4,
                        'destination'=>Pdf::DEST_DOWNLOAD,
                        'cssFile'=>Yii::$app->basePath.'/web/css/pdf.css',
                        'filename'=>Yii::$app->name.' - '.$data->first_name.' '.$data->last_name,
                        'options' => [
                            'title' => $data->first_name.' '.$data->last_name
                        ],
                        'methods' => [
                            'SetHeader' => ['Generated By: '.Yii::$app->name.' ||Generated On: ' . date("F d, Y")],
                            'SetFooter' => ['|Page {PAGENO}|'],
                        ]
                    ]);
                    return $pdf->render();
                } else {
                    Yii::$app->session->setFlash('error', 'This user is Company');
                }
            }else{
                Yii::$app->session->setFlash('error', 'This user does not exist');
            }
        }

        return $this->render('seaman-export', [
            'model' => $model,
        ]);
    }


    public function actionLoadseaman()
    {
        $link = str_replace('http://','',Yii::$app->request->get('id'));
        $link = explode('/',$link);
        $n = count($link);
        $pid = str_replace('id','',$link[$n-1]);
        $id = Profile::findOne($pid)->user_id;
        $seaman = Seaman::findOne(['user_id'=>$id])->id;
        $scans = SeamanDocumentScan::findAll(['seaman_id'=>$seaman]);
        $docs = [];
        foreach($scans as $item){
            $coc = SeamanCertificateOfCompetency::getAllByScan($item->id);
            foreach($coc as $c){
                $docs[] = $c;
            }
            $tr = SeamanTravelDocument::getAllByScan($item->id);
            foreach($tr as $t){
                $docs[] = $t;
            }
            $med = SeamanMedicalDocument::getAllByScan($item->id);
            foreach($med as $m){
                $docs[] = $m;
            }
            $prof = SeamanCertificateOfProficiency::getAllByScan($item->id);
            foreach($prof as $p){
                $docs[] = $p;
            }
        }
        if(!empty($docs)) {
            $html = '';
            foreach ($docs as $item) {
                $html .= '<option value="' . $item->scan_id . '">' . $item->docType['name'] . '</option>';
            }
            echo $html;
        }
    }

    public function actionMails()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $data = CompanyContact::find()->select('email')->andFilterWhere(['like', 'email', Yii::$app->request->get('term')])->all();
        $arr = ArrayHelper::map($data,'email','email');
        return $arr;
    }

    public function actionTerms()
    {
        $this->layout="dashboard";
        $model = new TermsOfService();
        $data = $model->find()->orderBy(['position'=>SORT_ASC])->all();
        return $this->render('terms',[
            'model'=>$model,
            'data'=>$data
        ]);
    }

    public function actionTermsform()
    {
        $model = new TermsOfService();
        $data = '';
        if($model->load(Yii::$app->request->get('id'))){
           $data = $model->findOne(Yii::$app->request->get('id'));
        }
        if($model->load(Yii::$app->request->post())){
            $post = Yii::$app->request->post('TermsOfService');
            if(!empty($post['id'])){
                $updete_model = TermsOfService::findOne($post['id']);
                $updete_model->section_name = $post['section_name'];
                $updete_model->text = $post['text'];
                $updete_model->save();
            }else{
                $model = new TermsOfService();
                $model->section_name = $post['section_name'];
                $model->text = $post['text'];
                $model->save();
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        return $this->renderAjax('terms-form',[
            'model'=>$model,
            'data'=>$data
        ]);
    }

    public function actionSavetermorder()
    {
        $model = new TermsForm();
        $data = Yii::$app->request->get();
        $model->updatePosition($data);
    }

    public function actionGetDocs($id)
    {
        $uid = Profile::findOne($id)->user_id;
        $model = Seaman::findOne(['user_id' => $uid]);
        $options = '';
        $data_key = ['competency', 'travelDocs'];
        foreach ($data_key as $keyname) {
            $keyitem = $model->{$keyname};
            if (is_array($keyitem)) {
                foreach ($keyitem as $item) {
                    if (!empty($item->scan_id)) {
                        $options .= '<option value="' . $item->id . '-' . $item->scan_id . '">' . $item->docType->name . '</option>';
                    }
                }
            } else {
                echo $keyitem->scan_id;
                echo "<br>";
            }
            echo $options;
        }
    }
    public function actionParticulars()
    {
        $this->layout = "dashboard";
        $model = new Seaman();

        $query = new ActiveQuery(Seaman::className());
        $error = null;
        if(Yii::$app->request->get('link')){

views/dashboard/users/_info.php
<?php
use yii\helpers\Html;

/* @var $model app\models\Users */
?>

<?php
$profile_picture_url = null;
$email = null;
$fullname = null;


if ($model->account_type_id == 1) {
    $profile_picture_url = !empty($model->seaman->profile_picture) ? "/images/seaman/photo/small/" . $model->seaman->profile_picture : "/images/seaman/nocv.png";
    $email = $model->email;
    $fullname = $model->seaman->first_name . ' ' . $model->seaman->last_name;
} elseif ($model->account_type_id == 2) {
    $profile_picture_url = !empty($model->seaman->profile_picture) ? "/images/companies/logos/small/" . $model->company->profile_picture : "/images/companies/logos/noimage.jpg";
    $email = $model->email;
    $fullname = $model->company->name;
}

?>

<table class="table-bordered">
    <tr>
        <th>User</th>
        <td>
            <div class="img company-logo">
                <img src="<?= $profile_picture_url; ?>" alt="<?= $fullname; ?>">
            </div>
            <div class="detales">
                <h3 class="full-name"><?= $fullname; ?></h3>
                <div class="mail"><?= $email; ?></div>
            </div>
        </td>
    </tr>
    <tr>
        <th>User ID</th>
        <td>
            <?= $model->id; ?>
        </td>
    </tr>
    <tr>
        <th>Account type</th>
        <td>
            <?= !is_null($model->user_account_type_id) ? $model->userAccountType->name : ''; ?>
        </td>
    </tr>
    <tr>
        <th>Last seen</th>
        <td class="last-seen">
            <?php $time = floor((time() - strtotime($model->last_seen))/60); ?>
            <?= strtotime($model->last_seen); ?>
        </td>
    </tr>
    <tr>
        <th>Balance</th>
        <td><?= $model->balance; ?></td>
    </tr>
</table>

<?php
$this->registerCss('
.table-bordered{
width: 100%;
}
.table-bordered th{
    padding: 15px;
    text-align: right;
}
');

$this->registerJs('
    if (navigator.cookieEnabled)
       a = parseInt(- new Date().getTimezoneOffset());
    var t = parseInt($(\'.last-seen\').text());
    var m = moment(t,\'X\').fromNow();
    $(\'.last-seen\').text(m);
', \yii\web\View::POS_READY)
 ?>

views/dashboard/users/_item.php
<?php
use yii\helpers\Url;
use app\models\Currency;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Users';
?>


<?php
$profile_picture_url = null;
$email = null;
$fullname = null;


if ($model->role=='seaman') {
    $profile_picture_url = !empty($model->seaman->profile_picture) ? "/images/seaman/photo/small/" . $model->seaman->profile_picture : "/images/seaman/nocv.jpg";
    $email = $model->email;
    $fullname = $model->seaman->first_name . ' ' . $model->seaman->last_name;
} elseif ($model->role=='company') {
    $profile_picture_url = !empty($model->seaman->profile_picture) ? "/images/companies/logos/small/" . $model->company->profile_picture : "/images/companies/logos/noimage.jpg";
    $email = $model->email;
    $fullname = $model->company->name;
}

?>

<div class="info pull-left">
    <span class="user-none">
    <div class="img company-logo user-image <?php if($model->role=='seaman'): ?>img-circle<?php endif; ?>">
        <img src="<?= $profile_picture_url; ?>" alt="<?= $fullname; ?>">
    </div>
    <div class="detales user-details">
        <h3 class="full-name"><?= $fullname; ?></h3>
        <div class="mail"><?= $email; ?></div>
    </div>
    </span>
    <div class="btn-group btn-admin">
        <button type="button" class="btn btn-primary db-show-info" data-user-id="<?= $model->id; ?>">View</button>
        <?php if($model->role != 'admin'): ?>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <?php if($model->role == 'seaman'): ?>
                <li><a href="#" class="edit-user" data-user-id="<?= $model->id; ?>">
                        Edit user
                </a></li>
                <?php else: ?>
                    <li><a href="#" class="verify-user" data-user-id="<?= $model->id; ?>">
                        Verify user
                    </a></li>
                <?php endif; ?>
                <li><a href="#" class="delete-user" data-user-id="<?= $model->id; ?>">Delete user</a></li>
                <li><a href="#" class="delete-ban-user" data-user-id="<?= $model->id; ?>">Delete & ban user</a></li>
            </ul>
        <?php endif; ?>
    </div>
</div>

views/dashboard/users/_item_old.php
<?php
use yii\helpers\Url;
use app\models\Currency;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Users';
?>

<?php if($model->account_type_id==1): ?>
    <div class="info pull-left">
        <div class="img profile-img">
            <?php if(!empty($model->seaman->profile_picture)): ?>
                <img src="/images/seaman/photo/small/<?=$model->seaman->profile_picture?>" alt="<?=$model->seaman->first_name?> <?=$model->seaman->last_name?>">
            <?php else: ?>
                <img src="/images/seaman/nocv.jpg" alt="">
            <?php endif; ?>
        </div>
        <div class="detales">
            <h3 class="full-name"><?=$model->seaman->first_name?> <?=$model->seaman->last_name?></h3>
            <div class="mail"><?=$model->email;?></div>
        </div>
    </div>


<?php elseif($model->account_type_id==2): ?>
    <div class="info pull-left">
        <div class="img company-logo">
            <?php if(!empty($model->company->profile_picture)): ?>
                <img src="/images/companies/logos/small/<?=$model->company->profile_picture?>" alt="<?=$model->company->name?>?>">
            <?php else: ?>
                <img src="/images/companies/logos/noimage.jpg" alt="">
            <?php endif; ?>
        </div>
        <div class="detales">
            <h3 class="full-name"><?=$model->company->name?></h3>
            <div class="mail"><?=$model->email;?></div>
        </div>
    </div>
<?php elseif($model->account_type_id==0): ?>

<?php endif; ?>

views/dashboard/users/_modal_delete.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'delete',
    'header' => 'Delete this user?',
    'footer' => '<button class="btn btn-danger btn-delete-user">Delete user</button><button class="btn btn-default" data-dismiss="modal">Close</button>',
]); ?>

<?php Modal::end(); ?>

views/dashboard/users/_modal_delete_ban.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'delete_ban',
    'header' => 'Delete this user?',
    'footer' => '<button class="btn btn-danger btn-delete-ban-user">Delete & ban user</button><button class="btn btn-default" data-dismiss="modal">Close</button>',
]); ?>

<?php Modal::end(); ?>

views/dashboard/users/_modal_delete_ban_confirm.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'delete_ban_confirm',
    'header' => 'Warning',
    'footer' => '<button class="btn btn-danger btn-confirm-delete-ban-user">Delete & ban user</button><button class="btn btn-default" data-dismiss="modal">Close</button>',
]); ?>

<?php Modal::end(); ?>

views/dashboard/users/_modal_delete_confirm.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'delete_confirm',
    'header' => 'Warning',
    'footer' => '<button class="btn btn-danger btn-confirm-delete-user">Delete user</button><button class="btn btn-default" data-dismiss="modal">Close</button>',
]); ?>

<?php Modal::end(); ?>

views/dashboard/users/_modal_edit.php
<?php

use app\models\UserAccountType;
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $changePassword app\models\ChangeEmail */
/* @var $changeEmail app\models\ChangePassword */


?>
<?php $form = ActiveForm::begin(['id' => 'form-edit-account']); ?>
<?php Modal::begin([
    'id' => 'edit_account',
    'header' => 'Edit user',
    'footer' => '<button type="submit" class="btn btn-primary">Save changes</button><button type="button" class="btn cancel" data-dismiss="modal">Cancel</button>',
]); ?>


<?php // echo Html::dropDownList('user_account_type', null, UserAccountType::getAccountType(), ['class' => 'form-control']); ?>
        <?= $form->field($changeEmail, 'new')->textInput(['class' => 'form-control']); ?>
<?= $form->field($changePassword, 'new')->passwordInput(['class' => 'form-control'])->label('Password'); ?>
<?= $form->field($changePassword, 'new2')->passwordInput(['class' => 'form-control'])->label(false); ?>


<?php Modal::end(); ?>
<?php ActiveForm::end(); ?>

views/dashboard/users/_modal_info.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'view_account',
    'header' => 'User info',
    'footer' => '<button class="btn btn-primary" data-dismiss="modal">Close</button>',
]); ?>

<?php Modal::end(); ?>

<?php
$this->registerCss('
#view_account .modal-body{
padding: 0px;
}

#view_account .modal-footer{
    background-color: rgba(232, 230, 230, 0.47);
}
');
?>

views/dashboard/users/_modal_verify.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this yii\web\View */

?>

<?php Modal::begin([
    'id' => 'verify',
    'header' => 'Verify this user?',
    'footer' => '<button class="btn btn-primary btn-verify" data-user-id="">Verify user</button><button class="btn btn-default"  data-dismiss="modal">Cancel</button>',
]); ?>

<?php Modal::end(); ?>